#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

feh --bg-fill ~/Pictures/Wallpapers/girl.jpg
picom &
~/.config/polybar/launch.sh 

bspc monitor -d 1 2 3 4 5 6 7 
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color		      "#e5e9f0"
bspc config active_border_color	        "#e5e9f0"
bspc config focused_border_color	      "#2492e0"
bspc config presel_feedback_color	      "#b48ead"
bspc config urgent_border_color 	      "#ebcb8b"

bspc rule -a firefox desktop='^2'
bspc rule -a discord desktop='^3'
bspc rule -a spotify desktop='^4'
bspc rule -a code desktop='^5'

wm-restack=bspwm

